lecture/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('todo/', include('todo.urls')),
    path('admin/', admin.site.urls),
]

todo/urls.py
from django.urls import path

from .views import createitem, index, detail, createlist, deletelist, deleteitem, updatelist, updateitem

app_name='todo'
urlpatterns = [
    path('', index, name='index'),
    path('<int:list_id>/', detail, name='list_details'),
    path('createlist/', createlist, name='list_create'),
    path('createitem/', createitem, name='item_create'),
    path('delete/<int:list_id>/', deletelist, name="list_delete" ),
    path('<int:list_id>/delete/<int:item_id>/', deleteitem, name='item_delete'),
    path('update/<int:list_id>/', updatelist, name='list_update'),
    path('<int:List_id>/update/<int:item_id>/', updateitem, name = 'item_update'),
    path('<int:List_id>/createitem/', createitem, name = 'create_item'),
]

polls/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
import datetime
from django.utils.timezone import now
from django.db.utils import IntegrityError
# Create your models here.

"""

List - eg. IMG TODO LIST, cad TODO list
Item - what task it is.

"""
# database model structure


# table
class TodoList(models.Model):
 
    list_name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return f"{self.list_name}"

# table
class TodoItem(models.Model):

    # table_attributes -->columns
    title = models.CharField(max_length=100)
    checked = models.BooleanField(default=False)
    due_date= models.DateTimeField(default=datetime.datetime.now())

    # foreignkey 
    todo_list = models.ForeignKey(to=TodoList, on_delete=models.CASCADE)
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['title', 'todo_list'], name='name of constraint')
        ]
    def __str__(self):
        return f"{self.todo_list.list_name}: {self.title}"

polls/views.py
from django.shortcuts import render

# Create your views here.

todo/views.py
from django.db.utils import Error
from django.http.response import HttpResponseNotAllowed
from django.shortcuts import render
from django.http import HttpResponse,Http404
from django.template import loader

from .models import TodoList
from .models import TodoItem
from django.db import IntegrityError


# Create your views here.

#->before template
# def index(request):
#     todolists = TodoList.objects.all()
#     list_items=TodoItem.objects.all()

#     output=', '.join(item.title for item in list_items) 
#     return HttpResponse(output)

# after template
def index(request):
    todolists = TodoList.objects.all()
    items = TodoItem.objects.all()
    template = loader.get_template('todo/index.html')
    context = {
        'todolists': todolists,
        'todoitems': items,
    }

    return HttpResponse(template.render(context,request)) #this or->
    #return render(request, 'todo/index.html',context)


def detail(request,list_id):
    try:
        todolist=TodoList.objects.get(id=list_id)
    except:
        raise Http404("This List Does not exist")
    items_list=TodoItem.objects.filter(todo_list=todolist)
    context={
        'todolist':todolist,
        'items_list':items_list
    }
    return render(request, 'todo/detail.html',context)


def createlist(request):
    if request.method == "GET":
        return render(request, 'todo/createlist.html')
    try:
        name = request.POST["name"]
        TodoList.objects.create(list_name=name)
        lists = TodoList.objects.all()
        context = {
            'todolists': lists,
        }
        return render(request, 'todo/index.html', context)
    except IntegrityError:
        raise Error("Error: List name already exists")


def createitem(request, List_id=0):
    if request.method == "GET":
        if List_id == 0:
            todolists = TodoList.objects.all()
            items = TodoItem.objects.all()
            context = {
            'todolists': todolists,
            'todoitems': items,
            }
            return render(request, 'todo/createitem.html', context)
            
        else:
            todolists = TodoList.objects.filter(id = List_id)
            items = TodoItem.objects.all()
            context = {
            'todolists': todolists,
            'todoitems': items,
            }
            return render(request, 'todo/createitem.html', context)
    try:
        title_name=request.POST['title']
        duedate=request.POST['due_date']
        list_id=int(request.POST['list_id'])
        check=request.POST['checked']
        t=TodoList.objects.get(id = list_id)
        if check=="yes":
            TodoItem.objects.create(title=title_name,checked=True,due_date=duedate,todo_list=t)
        else:
            TodoItem.objects.create(title=title_name,checked=False,due_date=duedate,todo_list=t)
        lists = TodoList.objects.all()
        context = {
            'todolists':lists,
        }
        return render(request, 'todo/index.html', context)
    except IntegrityError:
        raise Error("Item name already exitst in given list")
def deletelist(request, list_id):
    try:
        todolist=TodoList.objects.get(id=list_id)
    except:
        raise Http404("This List Does not exist")
    todolist.delete()
    todolists = TodoList.objects.all()
    items = TodoItem.objects.all()
    template = loader.get_template('todo/index.html')
    context = {
        'todolists': todolists,
        'todoitems': items,
    }
    return HttpResponse(template.render(context,request))    
def deleteitem(request, list_id, item_id):
    try:
        todoitem=TodoItem.objects.get(id=item_id)
    except:
        raise Http404("This Item Does not exist")
    todoitem.delete()
    try:
        todolist=TodoList.objects.get(id=list_id)
    except:
        raise Http404("This List Does not exist")
    items_list=TodoItem.objects.filter(todo_list=todolist)
    context={
        'todolist':todolist,
        'items_list':items_list
    }
    return render(request, 'todo/detail.html',context)
def updatelist(request, list_id):
    try:
        todolist=TodoList.objects.get(id=list_id)
    except:
        raise Http404("This List Does not exist")
    context={
        'todolist':todolist,
    }
    if request.method == "GET":
        return render(request, 'todo/updatelist.html', context)
    name = request.POST["name"]
    todolist.list_name=name
    todolist.save()
    todolists = TodoList.objects.all()
    items = TodoItem.objects.all()
    template = loader.get_template('todo/index.html')
    context = {
        'todolists': todolists,
        'todoitems': items,
    }
    return HttpResponse(template.render(context,request)) 

def updateitem(request, item_id, List_id):
    try:
        todoitem = TodoItem.objects.get(id = item_id)
    except:
        raise Http404("This item does not exist")
    try:
        Todolist = TodoList.objects.get(id = List_id)
    except:
        raise Http404("This List does not exist")
    if request.method == "GET":
        todolists = TodoList.objects.all()
        context={
            'todoitem':todoitem,
            'todolists':todolists,
            'Todolist': Todolist,
        }
        return render(request, 'todo/updateitem.html', context)
    title_name=request.POST['title']
    duedate=request.POST['due_date']
    check=request.POST['checked']
    if check == "yes":
        todoitem.title = title_name
        todoitem.save()
        todoitem.due_date = duedate
        todoitem.save()
        todoitem.checked = True
        todoitem.save()
        todoitem.save()
    else:
        todoitem.title = title_name
        todoitem.save()
        todoitem.due_date = duedate
        todoitem.save()
        todoitem.checked = False
        todoitem.save()
        todoitem.save()
    items_list=TodoItem.objects.filter(todo_list=Todolist)
    context={
        'todolist':Todolist,
        'items_list':items_list
    }
    return render(request, 'todo/detail.html',context)

todo/templates/todo/createitem.html
<form action="{% url 'todo:item_create' %}" method="POST">
    {% csrf_token %}
    <fieldset>

        <h1>Create New Item</h1>
        <label for="title">Title: </label>
        <input type="text" name="title" id="title">
        <br><br>
        <label for="due_date">Due Date: </label>
        <input type="date" name="due_date" id="due_date">
        <br><br>
        <label for="list_id">Todo List: </label>
        <select id="list_id" name="list_id">
            {% for todolist in todolists %}
            <option value="{{todolist.id}}">{{todolist.list_name}}</option>
            {% endfor %}
        </select>
        <br><br>
        Checked:
        <br>
        <input type="radio" name="checked" value="yes">YES 
        <br>
        <input type="radio" name="checked" value="no">NO 
        <br><br>
        <input type="submit">
    </fieldset>


</form>

todo/templates/todo/createlist.html
<form action="{% url 'todo:list_create' %}" method="POST">
    {% csrf_token %}
    <fieldset>

        <h1>Create New List</h1>
        <input type="text" name="name" id="name">

        <input type="submit">
    </fieldset>


</form>

todo/templates/todo/detail.html
<h1>{{ todolist.list_name }}</h1>

<ul>

    {% for item in items_list %}

    <li>
       {{item.title}}:{{item.due_date}},{{item.checked}}|<a href="/todo/{{item.todo_list.id}}/delete/{{item.id}}">delete</a>|<a href = "/todo/{{item.todo_list.id}}/update/{{item.id}}">update</a> 
    </li>

    {% endfor %}
    <a href = "/todo/{{todolist.id}}/createitem">Click here to add new item</a>
</ul>

todo/templates/todo/index.html
{% if todolists %}

    <ul>
        {% for todolist in todolists %}
        <li><a href="/todo/{{todolist.id}}">{{todolist.list_name}}</a>|<a href="/todo/delete/{{todolist.id}}">delete</a>|<a href="/todo/update/{{todolist.id}}">update</a></li>
        {% endfor %}
    </ul>

{% endif %}
<a href="/todo/createlist">Click here to add a new list</a><br>
<a href="/todo/createitem">Click here to add a new item</a>

todo/templates/todo/updateitem.html
<form action="{% url 'todo:item_update' Todolist.id todoitem.id%}" method="POST">
    {% csrf_token %}
    <fieldset>

        <h1>Update Item</h1>
        <label for="title">Title: </label>
        <input type="text" name="title" id="title" value="{{todoitem.title}}">
        <br><br>
        <label for="due_date">Due Date: </label>
        <input type="date" name="due_date" id="due_date" value="{{todoitem.due_date}}">
        <br><br>
        Checked:
        <br>
        <input type="radio" name="checked" value="yes">YES 
        <br>
        <input type="radio" name="checked" value="no">NO 
        <br><br>
        <input type="submit">
    </fieldset>


</form>

todo/templates/todo/updatelist.html
<form action="{% url 'todo:list_update' todolist.id %}" method="POST">
    {% csrf_token %}
    <fieldset>

        <h1>Update List</h1>
        <input type="text" name="name" id="name" value="{{todolist.list_name}}">

        <input type="submit">
    </fieldset>


</form>